nextdeveloper-nl/iam

- src/Auth/Guards/TokenGuard.php
- src/Auth/Providers/IamUserProvider.php
- src/Database/Models/Users.php
- src/Helpers/UserHelper.php
- src/IAMServiceProvider.php
New authenticator driver and provider added
> New authenticator driver and provider added

- src/Database/Models/AccountUsers.php
There is a conflict in between iam_account_users (which is view) and iam_account_user (which is a relation table) we fixed this manually. But we need to fix it by generator.
> fixed table name

- src/Http/Middleware/Authenticate.php
Authenticate fixed for options requests
> Authenticate fixed for options requests

- src/Authorization/Roles/AbstractRole.php
- src/Authorization/Roles/AnonymousRole.php
- src/Authorization/Roles/IAuthorizationRole.php
- src/Authorization/Roles/MemberRole.php
- src/Authorization/Roles/SystemAdminRole.php
> Authorization enhanced

- src/Services/AbstractServices/AbstractUsersService.php
- src/Services/Registration/RegistrationService.php
- src/Services/RolesService.php
> Register user process changed

- src/Services/Registration/RegistrationService.php
- src/Services/RolesService.php
Registration service and roles services are changed
> Registration service and roles services are changed

- src/Helpers/UserHelper.php
- src/Services/AccountsService.php
- src/Services/Registration/RegistrationService.php
- Unnecessary cache removed
- Unnecessary event firing removed
- FixRoles on registration process removed, we let the roles management process on to the application
> Registration process changed

- src/Services/AbstractServices/AbstractUsersService.php
iam_user_id removed from create
> Regenerated

- src/Helpers/UserHelper.php
> Added has functionality

- src/Helpers/UserHelper.php
- getWithEmail now can return null
- applyUserFields rewritten much error free
> New Helper functionality added

- src/Authorization/Roles/AbstractRole.php
- src/Authorization/Roles/AnonymousRole.php
- src/Authorization/Roles/IAuthorizationRole.php
- src/Authorization/Roles/MemberRole.php
- src/Authorization/Roles/SystemAdminRole.php
- src/Services/RolesService.php
- Role management enhanced
- Role listing finished
> Module generated again

- src/Http/Middleware/AddIamParameters.php
Added new set of iam parameters; iamUserId and iamAccountId
> Add iam parameters are changed again

- src/Services/UsersService.php
Now we can create user for the given account.
> Create user for account added

- config/iam.php
- src/Http/Middleware/AddIamParameters.php
- src/Http/Middleware/Authenticate.php
- Add Iam parameters converted back because it creates unwanted behaviour
- Added Authorization bypass URLs
> Add Iam parameters converted back because it creates unwanted behaviour

- src/Exceptions/UnauthorizedException.php
Unauthorized exception is customized to return proper error message
> Unauthorized exception is customized

- src/Authorization/Roles/AbstractRole.php
- src/Authorization/Roles/IAuthorizationRole.php
- src/Helpers/UserHelper.php
Generic policies created for CRUD operations
> Generic policies created for CRUD operations

- src/Authorization/Roles/AbstractRole.php
We had a problem when we check create policy. Now this is fixed.
> policy checks fixed

- src/Authorization/Roles/AbstractRole.php
- src/Authorization/Roles/IamAdminRole.php
- src/Authorization/Roles/MemberRole.php
- src/Database/Scopes/AuthorizationScope.php
- src/Helpers/UserHelper.php
- src/Http/Middleware/AddIamParameters.php
Authorization mechanism is changed and enhanced
> Authorization roles fixed

- src/Http/Transformers/PublicUsersTransformer.php
> Public user transformer added

- src/Http/Middleware/Authorize.php
- src/Http/Transformers/PublicUsersTransformer.php
Authorization controls changed
> Authorization controls changed

- config/iam.php
- src/Services/AccountsService.php
Added domain change check to accounts
> Added domain change check to accounts

- src/Database/Models/AccountUsersPerspective.php
- src/Database/Observers/AccountUsersPerspectiveObserver.php
- src/Http/Controllers/AccountUserPerspective/AccountUserPerspectiveController.php
- src/Http/Transformers/AbstractTransformers/AbstractAccountUserPerspectiveTransformer.php
- src/Http/Transformers/AccountUserPerspectiveTransformer.php
- src/Services/AbstractServices/AbstractAccountUserPerspectiveService.php
- src/Services/UsersService.php
> File name changes made

- src/Database/Models/AccountUsersPerspective.php
- src/Http/Middleware/Authorize.php
Added public URI's to authorization
> Added public URI's to authorization

- src/Http/Middleware/Authorize.php
Authorize is updated for public requests
> Authorize is updated for public requests

- src/Database/Models/AccountTypes.php
- src/Database/Models/AccountUsers.php
- src/Database/Models/AccountUsersPerspective.php
- src/Database/Models/Accounts.php
- src/Database/Models/BackendDirectories.php
- src/Database/Models/Backends.php
- src/Database/Models/LoginLogs.php
- src/Database/Models/LoginMechanisms.php
- src/Database/Models/Permissions.php
- src/Database/Models/RolePermissions.php
- src/Database/Models/RoleUsers.php
- src/Database/Models/Roles.php
- src/Database/Models/UserAccounts.php
- src/Database/Models/UserRoles.php
- src/Database/Models/Users.php
> New model are added

- src/Services/AbstractServices/AbstractAccountOverviewsService.php
- src/Services/AbstractServices/AbstractAccountTypesService.php
- src/Services/AbstractServices/AbstractAccountUserPerspectiveService.php
- src/Services/AbstractServices/AbstractAccountUsersService.php
- src/Services/AbstractServices/AbstractAccountsOverviewsService.php
- src/Services/AbstractServices/AbstractAccountsPerspectiveService.php
- src/Services/AbstractServices/AbstractAccountsService.php
- src/Services/AbstractServices/AbstractBackendDirectoriesService.php
- src/Services/AbstractServices/AbstractLoginLogsService.php
- src/Services/AbstractServices/AbstractLoginMechanismsService.php
- src/Services/AbstractServices/AbstractPermissionsService.php
- src/Services/AbstractServices/AbstractRolePermissionsService.php
- src/Services/AbstractServices/AbstractRoleUsersService.php
- src/Services/AbstractServices/AbstractRolesService.php
- src/Services/AbstractServices/AbstractUserAccountsService.php
- src/Services/AbstractServices/AbstractUserRolesService.php
- src/Services/AbstractServices/AbstractUsersService.php
> Services revisited

- src/Helpers/UserHelper.php
- src/Services/RolesService.php
UserHelper and RoleHelper enhanced
> UserHelper and RoleHelper enhanced

- src/Http/Transformers/UsersTransformer.php
- src/Services/UsersService.php
- Users service fixed
- User transformer fixed
> Users service fixed

- src/Services/AccountsService.php
> My accounts list bug is fixed

- src/Authorization/Roles/IamSuccessManagerRole.php
IamSuccessManager DB_PREFIX is changed
> IamSuccessManager DB_PREFIX is changed

- src/Database/Models/Accounts.php
- src/Database/Models/Users.php
- src/Database/Models/UsersPerspective.php
- src/Http/Controllers/Users/MyUsersController.php
- src/Http/Transformers/AbstractTransformers/AbstractUsersPerspectiveTransformer.php
- src/Http/Transformers/UsersPerspectiveTransformer.php
> My profile is updated

- src/Helpers/UserHelper.php
- src/Http/Controllers/Users/MyUsersController.php
Users perspective bug fix made
> Users perspective bug fix made

- src/Database/Filters/AccountOverviewsQueryFilter.php
- src/Database/Filters/AccountUserPerspectiveQueryFilter.php
- src/Database/Filters/AccountUsersPerspectiveQueryFilter.php
- src/Database/Filters/AccountUsersQueryFilter.php
- src/Database/Filters/AccountsOverviewsQueryFilter.php
- src/Database/Filters/AccountsPerspectiveQueryFilter.php
- src/Database/Filters/AccountsQueryFilter.php
- src/Database/Filters/BackendDirectoriesQueryFilter.php
- src/Database/Filters/LoginMechanismsQueryFilter.php
- src/Database/Filters/PermissionsQueryFilter.php
- src/Database/Filters/RolePermissionsQueryFilter.php
- src/Database/Filters/RoleUsersQueryFilter.php
- src/Database/Filters/UserAccountsQueryFilter.php
- src/Database/Filters/UserRolesQueryFilter.php
- src/Database/Filters/UsersPerspectiveQueryFilter.php
- src/Database/Filters/UsersQueryFilter.php
- src/Services/AccountsService.php
IAM query filters updated & account update is fixed
> IAM query filters updated & account update is fixed

- src/Database/Models/Users.php
- src/Services/NinService.php
- src/Services/UsersService.php
[NIN service updated](https://github.com/nextdeveloper-nl/iam/commit/2d5f2f857c45dfbff74151d6527f76fd438bd181)
> NIN service updated

- src/Services/NinService.php
- src/Services/UsersService.php
[NIN validation fixed](https://github.com/nextdeveloper-nl/iam/commit/6de26ae097892cd98acb7a43f49bf3b547780d62)
[NIN validation added while NIN update](https://github.com/nextdeveloper-nl/iam/commit/ddfbe2392510d451c27fb648bace8462775c831a)
> NIN validation added while NIN update

- src/Helpers/UserHelper.php
UserHelper null role should be fixed by now
> UserHelper null role should be fixed by now

- src/Helpers/UserHelper.php
Return false when role does not exists for model
> Return false when role does not exists for model

- src/Http/Transformers/AbstractTransformers/AbstractAccountsPerspectiveTransformer.php
IAM Accounts perspective is updated
> IAM Accounts perspective is updated

- src/Services/AccountsService.php
Disabled can update domain feature
> Disabled can update domain feature

- src/Services/AccountsService.php
[Kick user from the team is added](https://github.com/nextdeveloper-nl/iam/commit/e8075073cd66c1fe5257fb323729abc366943acf)
> Kick user from the team is added

- src/Database/Models/Accounts.php
- src/Database/Models/Users.php
- src/Helpers/UserHelper.php
> Get account owner is added

- src/Envelopes/AccountCreatedEnvelope.php
- src/Exceptions/CannotFindAccountException.php
- src/Helpers/UserHelper.php
- src/Services/UsersService.php
> User Helper is updated

- src/Helpers/UserHelper.php
- src/Http/Middleware/AddIamParameters.php
- [User helper current account is fixed](https://github.com/nextdeveloper-nl/iam/commit/839f25a149d0fd46c0552388b4962c2ae0837f06)
- [User helper fixed agains null bearer token](https://github.com/nextdeveloper-nl/iam/commit/8fccb5c3910850cf0197abf382d6c3bb0226b8e2)
> User helper fixed agains null bearer token

- src/Helpers/UserHelper.php
- src/Services/RolesService.php
User helper  account bug fixed
> User helper  account bug fixed

- src/Helpers/UserHelper.php
Fixing role is removed from UserHelper get roles
> Fixing role is removed from UserHelper get roles

- src/Database/Filters/AccountOverviewsQueryFilter.php
- src/Database/Filters/AccountUserPerspectiveQueryFilter.php
- src/Database/Filters/AccountsOverviewsQueryFilter.php
- src/Database/Filters/BackendDirectoriesQueryFilter.php
- src/Database/Filters/BackendsQueryFilter.php
- src/Database/Filters/UserAccountsQueryFilter.php
- src/Database/Filters/UserRolesQueryFilter.php
> Like changed to ilike

- src/Database/Models/Accounts.php
- src/Database/Models/Users.php
- src/Helpers/UserHelper.php
> isTeamOwner method introduced

- src/Helpers/UserHelper.php
> UserHelper updated

- src/Database/Models/Accounts.php
- src/Database/Models/Users.php
- src/Helpers/UserHelper.php
> User helper updated

- src/Helpers/UserHelper.php
UserHelper error messages updated
> UserHelper error messages updated

- src/Authorization/Roles/MemberRole.php
- src/Services/AccountsService.php
Member role updated & Iam get my accounts added order by
> Member role updated & Iam get my accounts added order by

- src/Authorization/Roles/MemberRole.php
- src/Http/Transformers/AbstractTransformers/AbstractAccountsPerspectiveTransformer.php
- src/Http/Transformers/AccountsPerspectiveTransformer.php
- src/Services/AccountsService.php
- [Add RefreshTokenCommand and update dependencies](https://github.com/nextdeveloper-nl/iam/commit/ccd6e0f14cf043dff4ffc388c5fbf1ac88a46e8a)
- [Iam Account Perspective updated](https://github.com/nextdeveloper-nl/iam/commit/530a7899bf5174de3e395b9c5e7a5ad36974b7ef)
> Add RefreshTokenCommand and update dependencies 

- src/Http/Transformers/AccountsPerspectiveTransformer.php
Iam Account Perspective updated
> Iam Account Perspective updated

- src/Http/Requests/Accounts/AccountsCreateRequest.php
- src/Http/Requests/Accounts/AccountsUpdateRequest.php
[Profile image url is added to request validators](https://github.com/nextdeveloper-nl/iam/commit/c220be52aed731329cfef5158535a52384be8154)
> Profile image url is added to request validators

- src/Services/AbstractServices/AbstractAccountOverviewsService.php
- src/Services/AbstractServices/AbstractAccountTypesService.php
- src/Services/AbstractServices/AbstractAccountUserPerspectiveService.php
- src/Services/AbstractServices/AbstractAccountUsersPerspectiveService.php
- src/Services/AbstractServices/AbstractAccountUsersService.php
- src/Services/AbstractServices/AbstractAccountsOverviewsService.php
- src/Services/AbstractServices/AbstractAccountsPerspectiveService.php
- src/Services/AbstractServices/AbstractAccountsService.php
- src/Services/AbstractServices/AbstractBackendDirectoriesService.php
- src/Services/AbstractServices/AbstractLoginLogsService.php
- src/Services/AbstractServices/AbstractLoginMechanismsService.php
- src/Services/AbstractServices/AbstractPermissionsService.php
- src/Services/AbstractServices/AbstractRolePermissionsService.php
- src/Services/AbstractServices/AbstractRoleUsersService.php
- src/Services/AbstractServices/AbstractRolesService.php
- src/Services/AbstractServices/AbstractUserAccountsService.php
- src/Services/AbstractServices/AbstractUserRolesService.php
- src/Services/AbstractServices/AbstractUsersPerspectiveService.php
- src/Services/AbstractServices/AbstractUsersService.php
> Pagination is fixed

- src/Database/Scopes/AuthorizationScope.php
- src/Helpers/UserHelper.php
- src/Http/Middleware/AddIamParameters.php
Authorization scope bug is fixed temporarily
> Authorization scope bug is fixed temporarily

- src/Helpers/UserHelper.php
Removed set as user and account log
> Removed set as user and account log

- src/Helpers/UserHelper.php
Get leo owner account function added
> Get leo owner account function added

- src/Helpers/UserHelper.php
[Admin functions added to UserHelper](https://github.com/nextdeveloper-nl/iam/commit/1b5b5b3ef6282bbb1cf087c6de0ae96031e512eb)
> Admin functions added to UserHelper

- src/Authorization/Roles/AbstractRole.php
- src/Helpers/UserHelper.php
[Dump removed](https://github.com/nextdeveloper-nl/iam/commit/cbc6e6de3d6c64f6a8648f2f08361766dfeb7b24)
[UserHelper set as admin fixed](https://github.com/nextdeveloper-nl/iam/commit/8c52cfdd263115f8e425ff1fb9dc9abc21b27fb6)
> UserHelper set as admin fixed

- src/Database/Models/Accounts.php
- src/Database/Models/Users.php
- src/Services/UsersService.php
New function added as createWithoutAccount to UserService
> New function added as createWithoutAccount to UserService

- src/Database/Models/Accounts.php
- src/Database/Models/Users.php
- src/Database/Scopes/AuthorizationScope.php
[Authorization scope updated for non available roles](https://github.com/nextdeveloper-nl/iam/commit/cd72273a5a02c9b0a6d6f6053b7fbbad6b31e60a)
> Authorization scope updated for non available roles

- src/Database/Scopes/AuthorizationScope.php
[If the role is not available, skip it](https://github.com/nextdeveloper-nl/iam/commit/c926540cfdcdd9a1284f56598ad0f31fd6bf6c6f)
> If the role is not available, skip it

- src/Http/Middleware/Authorize.php
[Authorization middleware is updated](https://github.com/nextdeveloper-nl/iam/commit/e37bbee4c40ce0246faeef17e6ec88b9c13ecc66)
> Authorization middleware is updated

- src/Helpers/UserHelper.php
UserHelper is now taking int for finding account
> UserHelper is now taking int for finding account

- src/Http/Requests/Accounts/AccountsUpdateRequest.php
[Account update is fixed](https://github.com/nextdeveloper-nl/iam/commit/f7e36e795c82a87d09465b5818b9a5d00565a7ae)
> Account update is fixed

- src/Database/Filters/AccountOverviewsQueryFilter.php
- src/Database/Filters/AccountTypesQueryFilter.php
- src/Database/Filters/AccountUserPerspectiveQueryFilter.php
- src/Database/Filters/AccountUsersPerspectiveQueryFilter.php
- src/Database/Filters/AccountsOverviewsQueryFilter.php
- src/Database/Filters/AccountsPerspectiveQueryFilter.php
- src/Database/Filters/AccountsQueryFilter.php
- src/Database/Filters/BackendDirectoriesQueryFilter.php
- src/Database/Filters/BackendsQueryFilter.php
- src/Database/Filters/LoginMechanismsQueryFilter.php
- src/Database/Filters/PermissionsQueryFilter.php
- src/Database/Filters/RolesQueryFilter.php
- src/Database/Filters/UserRolesQueryFilter.php
- src/Database/Filters/UsersPerspectiveQueryFilter.php
- src/Database/Filters/UsersQueryFilter.php
- src/Services/LoginMechanismsService.php
Search changed to insensitive case
> Search changed to incase sensitive

- src/Database/Models/Accounts.php
- src/Services/LoginMechanisms/AbstractLogin.php
[Remove old tokens is now working with expires_at](https://github.com/nextdeveloper-nl/iam/commit/4b46f4de6aefdb612adfad5f2bc46ec7db0073ee)
> Remove old tokens is now working with expires_at

- src/Http/Middleware/Authorize.php
[Authorization was returning 401 instead of 403](https://github.com/nextdeveloper-nl/iam/commit/d1cd19c72525cbe4f2916e4e16806643196e06c0)
> Authorization was returning 401 instead of 403

- src/Database/Models/Accounts.php
- src/Database/Models/Users.php
[Marketplace relations added](https://github.com/nextdeveloper-nl/iam/commit/0c1c1902a954c73548fd7378fde66a5537aaa029)
> Marketplace relations added

- src/Http/Middleware/AddIamParameters.php
[Add iam parameters skipped for public requests](https://github.com/nextdeveloper-nl/iam/commit/127b4256e1231abdb4da500281b3f742de2c6993)
> Add iam parameters skipped for public requests

- src/Authorization/Roles/MemberRole.php
- src/Http/Middleware/AddIamParameters.php
- src/Http/Middleware/Authenticate.php
- src/Http/Middleware/Authorize.php
[Authorization process fixed](https://github.com/nextdeveloper-nl/iam/commit/e3030df29d911ffac304304b092a57b6cb552d76)
[Public requests are fixed](https://github.com/nextdeveloper-nl/iam/commit/ebe34bcae36c35d50ab1755572c892b895494524)
> Public requests are fixed

- src/Http/Middleware/AddIamParameters.php
- src/Http/Middleware/Authenticate.php
- src/Http/Middleware/Authorize.php
[Authentication is fixed for perspectives](https://github.com/nextdeveloper-nl/iam/commit/22095c431779d0f7d1d60175bf020f4355610e93)
> Authentication is fixed for perspectives

- src/Helpers/UserHelper.php
- src/Http/Middleware/Authorize.php
[Common exception added for authorization](https://github.com/nextdeveloper-nl/iam/commit/ec910dc2de867b6508ecd7b0f79e29df0b665983)
[Blogs exception added to authorize](https://github.com/nextdeveloper-nl/iam/commit/2839d388083593d66f0194be2d267eeb48814206)
> Blogs exception added to authorize

- src/Services/NinService.php
[Nin service updated for null country](https://github.com/nextdeveloper-nl/iam/commit/06cacb7cdf05c9815c982afeadbd9abd10f82d26)
> Nin service updated for null country

- src/Helpers/UserHelper.php
[Removed log for public requestss](https://github.com/nextdeveloper-nl/iam/commit/e9be90ae3944c4721193371ba5a8ba811bc9fb38)
> Removed log for public requestss
